apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: buildpacks-deploy-env
spec:
  workspaces:
    - name: source-workspace
    - name: cache-workspace
  params:
    - name: repo-url
    - name: revision
      default: main
    - name: image
    - name: service
      description: Knative service name
    - name: source-directory
      description: A subpath in the directory where the source code to build is located
      default: ""
    - name: BUILDER_IMAGE
      default: paketobuildpacks/builder:base
    - name: env
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: source-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
    - name: build
      taskRef:
        name: buildpacks
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: source-workspace
        - name: cache
          workspace: cache-workspace
      params:
        - name: APP_IMAGE
          value: $(params.image)
        - name: SOURCE_SUBPATH
          value: $(params.source-directory)
        - name: BUILDER_IMAGE
          value: $(params.BUILDER_IMAGE)
    - name: config-map
      when:
        - input: "$(params.env)"
          operator: notin
          values: [""]
      taskRef:
        name: config-map
      runAfter:
        - build
      params:
        - name: env
          value: $(params.env)
        - name: service
          value: $(params.service)
    - name: deploy
      taskRef:
        name: kn
      params:
        - name: ARGS
          value:
            - "service"
            - "apply"
            - "$(params.service)"
            - "--image=$(params.image)@$(tasks.build.results.APP_IMAGE_DIGEST)"
            - "--env-from"
            - "cm:ksvc-$(params.service)"
