apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton
secrets:
  - name: docker-user-pass
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-knative
  namespace: default
rules:
  - apiGroups:
      - serving.knative.dev
    resources:
      - "*"
    verbs:
      - create
      - update
      - patch
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - update
      - patch
      - delete
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-knative
  namespace: default
subjects:
  - kind: ServiceAccount
    name: tekton
    namespace: default
roleRef:
  kind: Role
  name: tekton-knative
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-rolebinding
subjects:
  - kind: ServiceAccount
    name: tekton
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-roles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-clusterbinding
subjects:
  - kind: ServiceAccount
    name: tekton
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-clusterroles
