apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: build-deploy
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: gitrepositoryurl
      value: $(body.repository.url)
    - name: gittruncatedsha
      value: $(extensions.gittruncatedsha)
    - name: service
      value: "$(body.repository.name)-$(extensions.gitbranch)"
