apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: build-deploy
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: main
    - name: gitrepositoryurl
      description: The git repository url
    - name: gittruncatedsha
    - name: service
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: build-deploy-run-
      spec:
        serviceAccountName: tekton
        pipelineRef:
          name: build-deploy
        params:
          - name: revision
            value: $(tt.params.gitrevision)
          - name: repo-url
            value: $(tt.params.gitrepositoryurl)
          - name: image-tag
            value: $(tt.params.gittruncatedsha)
          - name: image
            value: docker.io/pmbanugo/$(tt.params.service)
          - name: service
            value: $(tt.params.service)
